Vagrant.configure("2") do |config|
config.vm.define "nhakkaouS" do |config|
    config.vm.box = "centos/8"
    config.vm.box_version = ">=8.1.1911"
    config.vm.box_check_update = true
    config.vm.network "public_network", ip: "192.168.42.110"
    config.vm.hostname = "nhakkaouS"
    config.vm.provision "k3s shell script", type: "shell", privileged: false,
    path: "script.sh"
  end
end