Vagrant.configure("2") do |config|
  # First Machine
  config.vm.box = "centos/7"
  config.vbguest.installer_options = { allow_kernel_upgrade: true }

  config.vm.define "nhakkaouS" do |sv|
    
    sv.vm.network "public_network", ip: "192.168.42.110"
    sv.vm.hostname = "nhakkaouS"
    sv.vm.synced_folder "./shared", "/vagrant_shared"
    sv.vm.provider "virtualbox" do |v|
      v.memory = 1024
      v.cpus = 1
    end
    sv.vm.provision "shell", path: "script.sh"
    # sv.trigger.after :up do |trigger|
    #   trigger.run_remote = {inline: "pwd"}
    #   trigger.run = {inline: "sudo cat /var/lib/rancher/k3s/server/token > /vagrant"}
    # end
  end
  # Second Machine
  config.vm.define "nhakkaouSW" do |sw|
    sw.vm.network "public_network", ip: "192.168.42.111"
    sw.vm.hostname = "nhakkaouSW"
    sw.vm.synced_folder "./shared", "/vagrant_shared"
    sw.vm.provider "virtualbox" do |v|
      v.memory = 512
      v.cpus = 1
    end
    sw.vm.provision "shell", path: "script2.sh"
  end  
end
